language: python
python:
  - "2.6"
  - "2.7"
script: nosetests
notifications:
  email:
    recipients:
      - pascal.cadotte+travis@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
